begin;

INSERT INTO users (username, password, name, surname, avatar, is_admin) VALUES
    ('username', crypt('12345', gen_salt('bf', 8)), 'Scott', 'Adams', 'http://pluh/meh.jpg', true),
    ('username1', crypt('12345', gen_salt('bf', 8)), 'Stephen', 'Diehl', 'http://pluh/monad.jpg', false),
    ('username2', crypt('12345', gen_salt('bf', 8)), 'Sean', ' Carroll', 'https://preposterousuniverse.com/quant.jpg', false),
    ('username3', crypt('12345', gen_salt('bf', 8)), 'Phil', 'Substring', 'https://daaaa.mn/it.jpg', false),
    ('username4', crypt('12345', gen_salt('bf', 8)), 'Douglas', 'Crockford', 'https://daaaa.mn/it.jpg', false),
    ('username5', crypt('12345', gen_salt('bf', 8)), 'Snoyberg', 'FPComplete', 'http://pluh/kek.jpg', false);

INSERT INTO authors (user_id, description) VALUES
    (1, 'Hey you'),
    (2, 'What I wish I knew'),
    (3, 'Quantum relativity itself'),
    (4, 'Well duh');

INSERT INTO categories (name, parent_id) VALUES
    ('cat1', null),
    ('cat2', 1),
    ('cat3', 1),
    ('cat4', 2),
    ('cat5', 3),
    ('cat6', 5),
    ('cat7', 4);

INSERT INTO tags (tag_name) VALUES
    ('tag1'),
    ('tag2'),
    ('tag3');

INSERT INTO articles (
        author,
        category_id,
        article_title,
        article_content,
        is_published,
        main_photo,
        additional_photos
    ) VALUES
    (1, 1, 'Loserthink', 'If you’re interested in expanding how you think things through, check out Loserthink.', true, 'asdjf',  array[]::text[]),
    (2, 2, 'How To Solve It', 'Polya', true, '', array['one link']::text[]),
    (4, 2, 'Oh my gooood.', 'No one ever really dies.', false, '', array['two', 'links']::text[]),
    (3, 1, 'Something Deeply Hidden', 'New book out!', false, 'main ph', array['two', 'links']::text[]),
    (2, 2, 'What I Wish I Knew When Learning Haskell', 'English.', false, '', array['three', 'eee', 'links']::text[]),
    (2, 2, 'Пыщ', 'Еей!', false, '', array['f', 'o', 'u', 'r']::text[]),
    (2, 2, 'Disparaged', 'So', false, 'main', array['thr', 'e', 'e']::text[]),
    (3, 1, 'The Big Picture', 'New book again!', false, 'main', array['f', 'o', 'u', 'r']::text[]),
    (4, 2, 'getArticlesBySu bstring test', 'in author name', true, 'main', array['thr', 'e', 'e']::text[]),
    (4, 2, 'getArticlesBySu bstring test', 'getArticlesBySubstring: in content', true, 'main', array['thr', 'e', 'e']::text[]),
    (2, 2, 'getArticlesBySubstring', 'test: in title', true, 'main', array['thr', 'e', 'e']::text[]);

update articles
set creation_date = timestamp '2020-12-09 20:20:20.666628'
where article_id = 1;

update articles
set creation_date = timestamp '2020-12-09 18:18:18.666628'
where article_id = 2;

update articles
set creation_date = timestamp '2020-12-09 11:11:11.666628'
where article_id = 3;

update articles
set creation_date = timestamp '2020-12-09 19:19:19.666628'
where article_id = 4;

update articles
set creation_date = timestamp '2020-12-09 12:12:12.666628'
where article_id = 5;

update articles
set creation_date = timestamp '2020-12-09 15:15:15.666628'
where article_id = 6;

update articles
set creation_date = timestamp '2020-12-09 14:14:14.666628'
where article_id = 7;

update articles
set creation_date = timestamp '2020-12-09 13:13:13.666628'
where article_id = 8;

INSERT INTO articles_tags (tag_id, article_id) VALUES
    (1, 1),
    (2, 1),
    (3, 1),
    (2, 2),
    (3, 3);

INSERT INTO articles_comments (article_id, user_id, comment_text) VALUES
    (1, 2, 'kek'),
    (1, 3, 'pluh'),
    (2, 4, 'meh');

commit;
